/* 
 * WebAPIJourney
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Jurisdiction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JurisdictionTests
    {
        // TODO uncomment below to declare an instance variable for Jurisdiction
        //private Jurisdiction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Jurisdiction
            //instance = new Jurisdiction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Jurisdiction
        /// </summary>
        [Test]
        public void JurisdictionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Jurisdiction
            //Assert.IsInstanceOfType<Jurisdiction> (instance, "variable 'instance' is a Jurisdiction");
        }

        /// <summary>
        /// Test the property 'Jurisdiction1'
        /// </summary>
        [Test]
        public void Jurisdiction1Test()
        {
            // TODO unit test for the property 'Jurisdiction1'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Test]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'ExternalMapCode'
        /// </summary>
        [Test]
        public void ExternalMapCodeTest()
        {
            // TODO unit test for the property 'ExternalMapCode'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Test]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }

    }

}
